# Generated by Django 4.0.4 on 2022-07-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_title_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Title',
            new_name='title',
        ),
    ]
