# Generated by Django 4.0.4 on 2022-07-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_title_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
