# Generated by Django 4.0.4 on 2022-07-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
