# Generated by Django 4.0.4 on 2022-07-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_remove_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
