# Generated by Django 4.0.4 on 2022-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_apply_created_at_apply_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='cv',
            new_name='CV',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
