# Generated by Django 4.0.4 on 2022-09-29 01:29

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to=job.models.image_upload),
            preserve_default=False,
        ),
    ]
